apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.0.1
          ports:
            - containerPort: 9000
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: TZ
              value: America/Anchorage
            - name: BASE_URL
              value: https://mealie.yourdomain.com
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_SERVER
              value: postgres
            - name: POSTGRES_USER
              value: mealie
            - name: POSTGRES_DB
              value: mealie
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie-app
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30925
  selector:
    app: mealie
