apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: mealie-app
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t   # base64 de 'admin@admin.com'
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4xMjM=        # base64 de 'admin123'
