apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: mealie-app
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30025  # Accesible en http://<minikube-ip>:30001
