apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: mealie-app
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
        
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mealie-app
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
