apiVersion: v1
kind: Secret
metadata:
  name: consumer-1-basic-auth
  namespace: kong
  labels:
    konghq.com/credential: basic-auth
stringData:
  username: consumer-1
  password: consumer-1-password
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-1
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/tags: silver-tier
custom_id: example-consumer-id
username: consumer-1
credentials:
- consumer-1-basic-auth