# Configuración para kube-prometheus-stack
kube-prometheus-stack:
  grafana:
    grafana.ini:
      server:
        root_url: "http://localhost:3000/"
      auth:
        disable_login_form: false
      auth.generic_oauth:
        verbose_logging: true
        enabled: true
        name: Keycloak
        allow_sign_up: true
        client_id: grafana 
        client_secret: 0HfA65iSMzgU3tU4sEruWKEubz4O7ZtA 
        scopes: openid email profile
        auth_url: http://localhost:30080/realms/grafana/protocol/openid-connect/auth
        token_url: http://keycloak.keycloak.svc.cluster.local:80/realms/grafana/protocol/openid-connect/token
        api_url: http://keycloak.keycloak.svc.cluster.local:80/realms/grafana/protocol/openid-connect/userinfo
        role_attribute_path: "contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'"      
        login_attribute_path: preferred_username
        name_attribute_path: name
        email_attribute_path: email

    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""
      accessMode: ReadWriteOnce
      annotations: {}

# Configuración para Loki
loki:
  # Configuración básica de Loki
  loki:
    auth_enabled: false
    commonConfig:
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
