apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcoa001/mealie.git
    #targetRevision: HEAD
    targetRevision: argo-branch
    path: monitoring-helm
    helm:
      valueFiles:
        - values.yaml
        - loki-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true