apiVersion: v1
kind: Secret
metadata:
  name: mealie-app-sa-token
  namespace: mealie-app
  annotations:
    kubernetes.io/service-account.name: mealie-app-sa
type: kubernetes.io/service-account-token
#data:
#  token: $(kubectl get secret mealie-app-secret -n mealie-app -o jsonpath='{.data.token}')
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-operator-sa-token
  namespace: mealie-db
  annotations:
    kubernetes.io/service-account.name: postgres-operator-sa
type: kubernetes.io/service-account-token
#data:
#  token: $(kubectl get secret mealie-app-secret -n mealie-app -o jsonpath='{.data.token}')
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-sa-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: monitoring-sa
type: kubernetes.io/service-account-token
#data:
#  token: $(kubectl get secret mealie-app-secret -n mealie-app -o jsonpath='{.data.token}')
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-sa-token
  namespace: mealie-db
  annotations:
    kubernetes.io/service-account.name: postgres-exporter-sa
type: kubernetes.io/service-account-token
#data:
#  token: $(kubectl get secret mealie-app-secret -n mealie-app -o jsonpath='{.data.token}')