apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: {{ .Release.Namespace }}
spec:
  args:
  - name: service-name
  - name: success-rate
  - name: interval
  - name: count
  
  metrics:
  - name: success-rate
    interval: "{{ args.interval }}"
    count: "{{ args.count }}"
    successCondition: result >= {{ args.success-rate }}
    provider:
      prometheus:
        address: http://prometheus-operated.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{service="{{ args.service-name }}", status=~"2.."}[5m])) 
          / 
          sum(rate(http_requests_total{service="{{ args.service-name }}"}[5m])) 
          * 100
