{{- if .Values.kong.basicAuth.enabled }}
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ .Values.kong.basicAuth.username }}
  namespace: {{ .Values.namespace }}
username: {{ .Values.kong.basicAuth.username }}
credentials:
  - {{ .Values.kong.basicAuth.username }}-basic-auth
{{- end }} 