{{- if .Values.kong.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kong.basicAuth.username }}-basic-auth
  namespace: {{ .Values.namespace }}
  labels:
    konghq.com/credential: basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.kong.basicAuth.username }}
  password: {{ .Values.kong.basicAuth.password }}
{{- end }} 