apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.secret.user | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.secret.db | b64enc }}
  POSTGRES_SERVER: {{ .Values.postgres.secret.server | b64enc }}
  POSTGRES_PORT: {{ .Values.postgres.secret.port | toString | b64enc }} 